server:
  port: 8082

debug: false

spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.ai.mcp.client.autoconfigure.McpClientAutoConfiguration
#      - org.springframework.ai.mcp.client.autoconfigure.McpToolCallbackAutoConfiguration
  application:
    name: rag-elasticsearch
  config:
    import:
      - optional:classpath:config/dev/application-mcp-dev.yml
      - optional:classpath:config/dev/application-query-rewrite-dev.yml
      - optional:classpath:config/dev/application-memory-dev.yml
      - optional:classpath:config/dev/application-langfuse-dev.yml
  ai:
    chat:
      observations:
        log-prompt: false    # 禁用Spring AI内置提示日志，使用自定义日志
        log-completion: false  # 禁用Spring AI内置完成日志
      client:
        observations:
          log-prompt: false    # 禁用Spring AI内置客户端提示日志，使用自定义日志
    openai:
      api-key: sk-dae20e2b5ec340a3bd0de1cc476c2894
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen3-max
      embedding:
        options:
          model: text-embedding-v1

    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: ai_loan1_
        similarity: cosine
        dimensions: 1536

    rag:
      retriever:
        type: bm25  # 可选值: hybrid, vector, bm25
      hybrid:
        top-k: 5
        rrf-k: 60
      bm25:
        top-n: 5
      vector:
        top-k: 5
        similarity-threshold: 0.85
      reranker:
        enabled: true
        endpoint: https://api.siliconflow.cn/v1/rerank
        model: BAAI/bge-reranker-v2-m3
        timeout-ms: 3000
        api-key: "sk-vcqgdvzbcchptznjpgcsyrfzrclvuvsidsrdpoyadgzgmtpg"
  elasticsearch:
    uris: http://127.0.0.1:9200
    username: elastic
    password: yingzi

app:
  dev-tests:
    enabled: false    # 禁用启动时自动执行的测试

management:
  tracing:
    sampling:
      probability: 1.0