# LangFuse 集成配置
# LangFuse 是一个开源的 LLM 可观测性平台，用于跟踪、分析和监控 AI 应用

# 启用 LangFuse 集成
langfuse:
  enabled: false  # 设置为 true 以启用 LangFuse 集成
  
  # LangFuse 服务器端点
  # 本地部署: http://localhost:3000/api/public
  # 云服务: https://cloud.langfuse.com/api/public
  endpoint: http://localhost:3000/api/public
  
  # 认证配置（必需）
  # 从 LangFuse 控制台获取这些密钥
  api:
    key: ""  # LangFuse API 密钥
  public:
    key: ""  # LangFuse 公钥
  
  # 采样配置
  sampling:
    probability: 1.0  # 采样概率 (0.0-1.0)，1.0 表示记录所有请求
    
  # 隐私配置
  privacy:
    record-inputs: true   # 是否记录输入数据
    record-outputs: true  # 是否记录输出数据
    record-errors: true   # 是否记录错误信息