# Memory Configuration - 通用配置模板
# 对话内存和TOP_K配置模板
#
# 开发环境配置：config/dev/application-memory-dev.yml
# 生产环境配置：config/prod/application-memory-prod.yml
#
# 注意：实际的内存配置在环境特定文件中定义
# 该文件仅作为配置参考模板

# spring:
#   ai:
#     chat:
#       memory:
#         max-messages: 10  # 最大保存的消息数量
#         top-k: 100       # TOP_K参数，用于控制检索的相关文档数量