# Query Rewriting Configuration - 通用配置模板
# 查询重写功能配置模板
# 
# 开发环境配置：config/dev/application-query-rewrite-dev.yml (默认启用)
# 生产环境配置：config/prod/application-query-rewrite-prod.yml (默认启用)
#
# 注意：实际的查询重写配置在环境特定文件中定义
# 该文件仅作为配置参考模板

# spring:
#   ai:
#     rag:
#       query-rewrite:
#         enabled: true  # 是否启用查询重写
#         custom-prompt-resource:  # 可选：自定义提示模板资源文件