spring:
  application:
    name: rag-elasticsearch
  profiles:
    active: dev
  config:
    import:
      - optional:classpath:config/dev/application-dev.yml
#      - optional:classpath:config/prod/application-prod.yml

logging:
  level:
    root: INFO
    org.springframework.boot.autoconfigure: WARN
    org.springframework.boot.actuate: WARN
    org.springframework.boot: WARN
    org.springframework: WARN
    com.spring.ai.app.rag.transformer.ContextualRewriteQueryTransformer: DEBUG
    com.spring.ai.app.rag.services.CustomerSupportAssistant: INFO
    com.spring.ai.app.rag.config.ObservationConfiguration: INFO
    com.spring.ai.app.rag.controller: DEBUG


