spring:
  application:
    name: rag-elasticsearch
  profiles:
    active: dev
  config:
    import:
      - optional:classpath:config/dev/application-dev.yml
#      - optional:classpath:config/prod/application-prod.yml

logging:
  level:
    com.spring.ai.app.rag.transformer.ContextualRewriteQueryTransformer: DEBUG
    com.spring.ai.app.rag.services.CustomerSupportAssistant: INFO
    com.spring.ai.app.rag.config.ObservationConfiguration: INFO


