# Profiles: create application-<profile>.yml files and activate via SPRING_PROFILES_ACTIVE or -Dspring.profiles.active
spring:
  application:
    name: rag-elasticsearch
  profiles:
    active: dev
  config:
    import:
      - optional:classpath:config/dev/application-dev.yml
#      - optional:classpath:config/prod/application-prod.yml

logging:
  level:
    com.spring.ai.tutorial.rag.transformer.ContextualRewriteQueryTransformer: DEBUG

              


