# Query Rewriting Configuration - 生产环境
# 生产环境下的查询重写配置

spring:
  ai:
    rag:
      query-rewrite:
        enabled: true  # 生产环境下启用查询重写
        # custom-prompt-resource: classpath:prompts/custom-rewrite-prompt.st  # 可选：自定义提示模板资源文件